####
#### FORMAT
#### VERSION;
####    PATH (relative to root folder of module)
####        LANGUAGE (php / ss / js / css / etc... to use more than one, you can use php|inc)
####            FindKey
####                R: replace with entry - you can leave empty to keep it as the find... in that case you should add a comment
####                C: comment - this makes it a complex replacement.
####                I: ignore case (default is case sensitive)

SS4:

    '.':

        '*':
            'mysite':
                R: "app"
            'Mysite':
                R: "App"
        php:
            ' implements flushable':
                R: ' implements Flushable'
            'HtmlEditorField':
                R: 'HTMLEditorField'
            '$this->process_combined_files();':
                R: '$this->processCombinedFiles();'
                C: this is likely to be part of the Requirements_Backend calls'
            '$this->path_for_file();':
                R: '$this->pathForFile();'
                C: this is likely to be part of the Requirements_Backend calls'
            'mysite/css/':
                R: "ModuleLoader::getModule('mysite')->getResource('css/UPGRADE-FIX-REQUIRED.css')->getRelativePath()"
                C: "Please review update and fix as required"
            'mysite/javascript/':
                R: "ModuleLoader::getModule('mysite')->getResource('javascript/UPGRADE-FIX-REQUIRED.js')->getRelativePath()"
                C: "Please review update and fix as required"
            'mysite/images/':
                R: "ModuleLoader::getModule('mysite')->getResource('images/UPGRADE-FIX-REQUIRED.png')->getRelativePath()"
                C: "Please review update and fix as required"

            ' extends Object':
                R: " extends ViewableData"
                C: "This used to extend Object, but object does not exist anymore. You can also manually add use Extensible, use Injectable, and use Configurable"
                I: true
            ' extends \Object':
                R: " extends ViewableData"
                C: "This used to extend Object, but object does not exist anymore. You can also manually add use Extensible, use Injectable, and use Configurable"
                I: true
            ' implements flushable':
                R: " implements Flushable"
                I: true
            ' extends Extension':
                R: " extends Extension"
                C: "Check for use of $this->anyVar and replace with $this->anyVar[$this->owner->ID] or consider turning the class into a trait"
                I: true
            ' extends DataExtension':
                R: " extends DataExtension"
                C: "Check for use of $this->anyVar and replace with $this->anyVar[$this->owner->ID] or consider turning the class into a trait"
                I: true

            'BASE_PATH':
                R: "Director::baseFolder()"
            'FRAMEWORK_DIR':
                R: "SilverStripe\\Core\\Manifest\\ModuleLoader::getModule('silverstripe/framework')->getResource('UPGRADE-FIX-REQUIRED.php')->getRelativePath()"
                C: "Please review update and fix as required"
                I: true
            'SSViewer::get_theme_folder()':
                R: "SilverStripe\\View\\ThemeResourceLoader::inst()->findThemedResource('UPGRADE-FIX-REQUIRED/styles.css', SilverStripe\\View\\SSViewer::get_themes())"
                C: "Please review update and fix as required"
                I: true
            'THEMES_DIR':
                R: "ThemeResourceLoader::inst()->getPath('UPGRADE-FIX-REQUIRED.foo.bar')"
                C: "Please review update and fix as required"
                I: true
            'Session::':
                R: "$this->getRequest()->getSession()"
                C: "the THIS needs to be an instance of Controller.  If this does not work, you may have access to the request itself, or use: Controller::curr()->getRequest."
            'SSViewer::set_source_file_comments(':
                R: "Config::inst()->set('SSViewer', 'source_file_comments', "
            'ReadOnlyField':
                R: "ReadonlyField"
            '->setError':
                R: "->setCustomValidationMessage"
                C: "This needs further investigation, see: https://github.com/silverstripe/silverstripe-framework/issues/8225"
            "Cache::factory(":
               R: "Injector::inst()->get("
               C: "ADD TO TOP OF CLASS: use Psr\\SimpleCache\\CacheInterface; add to key: CacheInterface::class.'.'"
            "$cache->load(":
                R: "$cache->get("
                C: "Check carefully and add some stuff to yml: https://docs.silverstripe.org/en/4/changelogs/4.0.0#cache"
            "$cache->save(":
                R: "$cache->set("
                C: "Check carefully KEY AND VALUE NEED TO BE SWAPPED: https://docs.silverstripe.org/en/4/changelogs/4.0.0#cache"
            "$cache->remove(":
                R: "$cache->delete("
                C: "Check carefully: https://docs.silverstripe.org/en/4/changelogs/4.0.0#cache"
            "$result->error(":
                R: "$result->addError("
            "Object::use_custom_class":
                R: ""
                C: "You need to move this code to yml, using SilverStripe\\Core\\Injector\\Injector\n  OldClass: NewClass"
            "_Controller extends PageController":
                R: "Controller extends PageController"
                C: "Remove the underscore in your classname - check all references!"
            "_Controller extends Page_Controller":
                R: "Controller extends Page_Controller"
                C: "Remove the underscore in your classname - check all references!"
            'THIRDPARTY_DIR."/jquery/jquery.js"':
                R: "'silverstripe/admin: thirdparty/jquery/jquery.js'"
            'THIRDPARTY_DIR . "/jquery/jquery.js"':
                R: "'silverstripe/admin: thirdparty/jquery/jquery.js'"
            "THIRDPARTY_DIR . '/jquery/jquery.js'":
                R: "'silverstripe/admin: thirdparty/jquery/jquery.js'"
            "THIRDPARTY_DIR.'/jquery/jquery.js'":
                R: "'silverstripe/admin: thirdparty/jquery/jquery.js'"
            'public function includeInHTML($templateFile, $content)':
                R: "public function includeInHTML($content)"
                I: true
        'yml':
            Director:
                R: "SilverStripe\\Control\\Director"
