####
#### FORMAT
#### VERSION;
####    PATH (relative to root folder of module)
####        LANGUAGE (php / ss / js / css / etc... to use more than one, you can use php|inc)
####            FindKey
####                R: replace with entry - you can leave empty to keep it as the find... in that case you should add a comment
####                C: comment - this makes it a complex replacement.
####                I: ignore case (default is case sensitive)

SS4:

    '.':

        '*':
            'mysite':
                R: "app"
            'Mysite':
                R: "App"
        php:

            'mysite/css/':
                R: "ModuleLoader::getModule('mysite')->getResource('css/UPGRADE-FIX-REQUIRED.css')->getRelativePath()"
                C: "Please review update and fix as required"
            'mysite/javascript/':
                R: "ModuleLoader::getModule('mysite')->getResource('javascript/UPGRADE-FIX-REQUIRED.js')->getRelativePath()"
                C: "Please review update and fix as required"
            'mysite/images/':
                R: "ModuleLoader::getModule('mysite')->getResource('images/UPGRADE-FIX-REQUIRED.png')->getRelativePath()"
                C: "Please review update and fix as required"

            ' extends Object':
                R: " extends ViewableData"
                C: "This used to extend Object, but object does not exist anymore. "
                I: true
            ' extends \Object':
                R: " extends ViewableData"
                C: "This used to extend Object, but object does not exist anymore. "
                I: true
            ' implements flushable':
                R: " implements Flushable"
                I: true
            ' extends Extension':
                R: " extends Extension"
                C: "Check for use of $this->anyVar and replace with $this->anyVar[$this->owner->ID] or consider turning the class into a trait"
                I: true
            ' extends DataExtension':
                R: " extends DataExtension"
                C: "Check for use of $this->anyVar and replace with $this->anyVar[$this->owner->ID] or consider turning the class into a trait"
                I: true

            'BASE_PATH':
                R: "Director::baseFolder()"
            'FRAMEWORK_DIR':
                R: "SilverStripe\\Core\\Manifest\\ModuleLoader::getModule('silverstripe/framework')->getResource('UPGRADE-FIX-REQUIRED.php')->getRelativePath()"
                C: "Please review update and fix as required"
                I: true
            'SSViewer::get_theme_folder()':
                R: "SilverStripe\\View\\ThemeResourceLoader::inst()->findThemedResource('UPGRADE-FIX-REQUIRED/styles.css', SilverStripe\\View\\SSViewer::get_themes())"
                C: "Please review update and fix as required"
                I: true
            'THEMES_DIR':
                R: "ThemeResourceLoader::inst()->getPath('UPGRADE-FIX-REQUIRED.foo.bar')"
                C: "Please review update and fix as required"
                I: true
            'Session::':
                R: "$this->getRequest()->getSession()"
                C: "the THIS needs to be an instance of Controller.  If this does not work, you may have access to the request itself, or use: Controller::curr()->getRequest."
            'SSViewer::set_source_file_comments(':
                R: "Config::inst()->set('SSViewer' ', 'source_file_comments', "
            'ReadOnlyField':
                R: "ReadonlyField"
            '->setError':
                R: "->setCustomValidationMessage"
                C: "This needs further investigation, see: https://github.com/silverstripe/silverstripe-framework/issues/8225"
            "Cache::factory('":
               R: "Injector::inst()->get(CacheInterface::class . '."
               C: "ADD TO TOP OF CLASS: use Psr\\SimpleCache\\CacheInterface;"
            "$cache->load(":
                R: "$cache->get("
                C: "Check carefully and add some stuff to yml: https://docs.silverstripe.org/en/4/changelogs/4.0.0#cache"
            "$cache->save(":
                R: "$cache->set("
                C: "Check carefully KEY AND VALUE NEED TO BE SWAPPED: https://docs.silverstripe.org/en/4/changelogs/4.0.0#cache"
            "$cache->remove(":
                R: "$cache->delete("
                C: "Check carefully: https://docs.silverstripe.org/en/4/changelogs/4.0.0#cache"

        'yml':
            Director:
                R: "SilverStripe\\Control\\Director"
# example of a path specific one
    'code/View/Requirements_Backend_For_Webpack.php':
        php:
            'public function includeInHTML($templateFile, $content)':
                R: "public function includeInHTML($content)"
                I: true
