####
#### FORMAT
#### VERSION;
####    LANGUAGE (php / ss / js / css / etc... to use more than one, you can use php|inc)
####        FindKey
####            R: replace with entry
####            C: comment - this makes it a complex replacement
####            P: more specific path (e.g. src/Foo/Bar or src/MyClass.php)
####            I: case insensitive (default is case sensitive)

SS4:
    php:
        mysite:
            R: 'app'
            I: true
        flusable:
            R: 'Flushable'
            I: true
        BASE_PATH:
            R: 'Director::baseFolder()'
        extends Extension:
            R: 'extends Extension'
            C: 'Check for use of $this->anyVar and replace with $this->anyVar[$this->owner->ID] or consider using a trait'
        extends DataExtension:
            R: 'extends Extension'
            C: 'Check for use of $this->anyVar and replace with $this->anyVar[$this->owner->ID] or consider using a trait'
