####
#### FORMAT
####    PATH (relative to root folder of module)
####        LANGUAGE (php / ss / js / css / etc... to use more than one, you can use php|inc)
####            FindKey
####                R: replace with entry - you can leave empty to keep it as the find... in that case you should add a comment
####                C: comment - this makes it a complex replacement.
####                I: ignore case (default is case sensitive)


'.':


    'yml':
        'Object':
            R: "SS_Object"
            C: "Check usage"
            I: true


    php:
        'extends Object':
            R: "extends SS_Object"
            C: "Check usage for Object (PHP) vs SS_Object (Silverstripe)"
            I: true
        'Object::':
            R: "SS_Object::"
            C: "Check usage for Object (PHP) vs SS_Object (Silverstripe)"
            I: true
