####
#### FORMAT
####    PATH (relative to root folder of module)
####        LANGUAGE (php / ss / js / css / etc... to use more than one, you can use php|inc)
####            FindKey
####                R: replace with entry - you can leave empty to keep it as the find... in that case you should add a comment
####                C: comment - this makes it a complex replacement.
####                I: ignore case (default is case sensitive)


'.':


    'yml':
        'Object':
            R: "SS_Object"
            C: "Check usage"
            I: true
        'svg':
            R: "svg"
            C: "SVG uploads are now disable in SS3.7: https://github.com/silverstripe/silverstripe-installer/commit/c25478bef75cc5482852e80a1fa6f1f0e6460e39, if you need to allow SVG uploads you need to update your configuration"
        'SVG':
            R: "SVG"
            C: "SVG uploads are now disable in SS3.7: https://github.com/silverstripe/silverstripe-installer/commit/c25478bef75cc5482852e80a1fa6f1f0e6460e39, if you need to allow SVG uploads you need to update your configuration"
        'html':
            R: "html"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'HTML':
            R: "HTML"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'htm':
            R: "htm"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'HTM':
            R: "HTM"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'xhtml':
            R: "xhtml"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'XHTML':
            R: "XHTML"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'xml':
            R: "xml"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'XML':
            R: "XML"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'swf':
            R: "swf"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'SWF':
            R: "SWF"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'Email':
            R: "Email"
            C: "Mailer no longer calls xml2raw on all email subject line, and now must be passed in via plain text. See: https://github.com/silverstripe/silverstripe-framework/commit/e47800917a5482b1dce455f4fbcb564ff73d7576"
            I: true
        'Convert::html2raw':
            R: "Convert::html2raw"
            C: "API Convert::html2raw no longer wraps text automatically. See: https://github.com/silverstripe/silverstripe-framework/commit/29e33475621fd9e4be20ecdea45d017bbd4f65f8"
            I: true



    'php':
        'extends Object':
            R: "extends SS_Object"
            C: "Check usage for Object (PHP) vs SS_Object (Silverstripe)"
            I: true
        'Object::':
            R: "SS_Object::"
            C: "Check usage for Object (PHP) vs SS_Object (Silverstripe)"
            I: true
        'HTTP::set_cache_age(':
            R: "HTTPCacheControl::singleton()->disableCache(); or HTTPCacheControl::singleton()->enableCache()->setMaxAge(60);"
            C: "HTTP Cache Header change - Opt-in Opt-out for http caching"
            I: true
        'create_new_password':
            R: "create_new_password"
            C: "This is depracated in SS4: https://github.com/silverstripe/silverstripe-framework/commit/f16d7e1838d834575738086326d1191db3a5cfd8, consider if there is a better way to implement this functionality"
            I: true
        'svg':
            R: "svg"
            C: "SVG uploads are now disable in SS3.7: https://github.com/silverstripe/silverstripe-installer/commit/c25478bef75cc5482852e80a1fa6f1f0e6460e39, if you need to allow SVG uploads you need to update your configuration"
        'SVG':
            R: "SVG"
            C: "SVG uploads are now disable in SS3.7: https://github.com/silverstripe/silverstripe-installer/commit/c25478bef75cc5482852e80a1fa6f1f0e6460e39, if you need to allow SVG uploads you need to update your configuration"
        'html':
            R: "html"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'HTML':
            R: "HTML"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'htm':
            R: "htm"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'HTM':
            R: "HTM"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'xhtml':
            R: "xhtml"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'XHTML':
            R: "XHTML"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'xml':
            R: "xml"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'XML':
            R: "XML"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'swf':
            R: "swf"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'SWF':
            R: "SWF"
            C: "Removed from default allowed uploadable file types, if you need to allow uploads for this file type you need to ou will need to append these to the File.allowed_extensions config as necessary."
        'ReadOnlyField':
            R: "ReadOnlyField"
            C: "Does this field contain HTML in the value? If so, you will need to check if the html has been escaped or is displaying correctly."
            I: true
        'SetWidth':
            R: "ScaleWidth"
            C: "Updated Image method names in PHP code and templates: https://docs.silverstripe.org/en/3/changelogs/3.2.0/"
            I: true
        'SetHeight':
            R: "ScaleHeight"
            C: "Updated Image method names in PHP code and templates: https://docs.silverstripe.org/en/3/changelogs/3.2.0/"
            I: true
        'SQLQuery':
            R: "SQLQuery"
            C: "Update code that uses SQLQuery, see https://docs.silverstripe.org/en/3/changelogs/3.2.0/#update-code-that-uses-sqlquery"
            I: true
        'DB::':
            R: "DB::"
            C: "Update code that interacts with SQL strings to use parameters, see https://docs.silverstripe.org/en/3/changelogs/3.2.0/#update-code-that-interacts-with-sql-strings-to-use-parameters"
            I: true
        'Email':
            R: "Email"
            C: "`Mailer` no longer calls `xml2raw` on all email subject line, and now must be passed in via plain text. See: https://github.com/silverstripe/silverstripe-framework/commit/e47800917a5482b1dce455f4fbcb564ff73d7576"
            I: true

    'ss':
        'SetWidth':
            R: "ScaleWidth"
            C: "Updated Image method names in PHP code and templates: https://docs.silverstripe.org/en/3/changelogs/3.2.0/"
            I: true
        'SetHeight':
            R: "ScaleHeight"
            C: "Updated Image method names in PHP code and templates: https://docs.silverstripe.org/en/3/changelogs/3.2.0/"
            I: true
