'EcommerceCountry_VisitorCountryProvider': 'EcommerceCountryVisitorCountryProvider'
'EcommerceSideReport_FeaturedProducts': 'EcommerceSideReportFeaturedProducts'
'EcommerceSideReport_EcommercePages': 'EcommerceSideReportEcommercePages'
'EcommerceSideReport_NoInternalIDProducts': 'EcommerceSideReportNoInternalIDProducts'
'EcommerceSideReport_NoPriceProducts': 'EcommerceSideReportNoPriceProducts'
'EcommerceSideReport_AllProducts': 'EcommerceSideReportAllProducts'
'EcommerceSideReport_NotForSale': 'EcommerceSideReportNotForSale'
'EcommerceSideReport_NoImageProducts': 'EcommerceSideReportNoImageProducts'
'EcommerceTaskBuilding_Extending': 'EcommerceTaskBuildingExtending'
'EcommerceTaskBuilding_Model': 'EcommerceTaskBuildingModel'
'OrderForm_Payment': 'OrderFormPayment'
'OrderForm_Feedback': 'OrderFormFeedback'
'OrderForm_Feedback_Validator': 'OrderFormFeedbackValidator'
'OrderFormAddress_Validator': 'OrderFormAddressValidator'
'ProductSearchForm_Validator': 'ProductSearchFormValidator'
'ShopAccountForm_PasswordValidator': 'ShopAccountFormPasswordValidator'
'ShopAccountForm_Validator': 'ShopAccountFormValidator'
'OrderModifierForm_Validator': 'OrderModifierFormValidator'
'OrderForm_Cancel_Validator': 'OrderFormCancelValidator'
'OrderStatusLogForm_Validator': 'OrderStatusLogFormValidator'
'Product_ProductImageUploadField': 'ProductProductImageUploadField'
'ProductSearchForm_Short': 'ProductSearchFormShort'
'OrderForm_Cancel': 'OrderFormCancel'
'Order_StatusEmail': 'OrderStatusEmail'
'Order_InvoiceEmail': 'OrderInvoiceEmail'
'Order_ErrorEmail': 'OrderErrorEmail'
'Order_Email': 'OrderEmail'
'Ecommerce_Dummy_Mailer': 'EcommerceDummyMailer'
'Order_ReceiptEmail': 'OrderReceiptEmail'
'OrderEmailRecord_Review': 'OrderEmailRecordReview'
'OrderModifierForm_Controller': 'OrderModifierFormController'
'OrderStatusLogForm_Controller': 'OrderStatusLogFormController'
'ShoppingCart_Controller': 'ShoppingCartController'
'CMSPageAddController_Products': 'CMSPageAddControllerProducts'
'OrderFilters_MemberAndAddress': 'OrderFiltersMemberAndAddress'
'OrderFilters_MustHaveAtLeastOnePayment': 'OrderFiltersMustHaveAtLeastOnePayment'
'OrderFilters_AroundDateFilter': 'OrderFiltersAroundDateFilter'
'OrderFilters_HasBeenCancelled': 'OrderFiltersHasBeenCancelled'
'OrderFilters_MultiOptionsetStatusIDFilter': 'OrderFiltersMultiOptionsetStatusIDFilter'
'Product_Image': 'ProductImage'
'Product_OrderItem': 'ProductOrderItem'
'OrderStep_Sent': 'OrderStepSent'
'OrderStep_Submitted': 'OrderStepSubmitted'
'OrderStep_SendAdminNotification': 'OrderStepSendAdminNotification'
'OrderStep_Archived': 'OrderStepArchived'
'OrderStep_Confirmed': 'OrderStepConfirmed'
'OrderStep_Paid': 'OrderStepPaid'
'OrderStep_SentReceipt': 'OrderStepSentReceipt'
'OrderStep_SentInvoice': 'OrderStepSentInvoice'
'OrderStep_Created': 'OrderStepCreated'
'OrderStatusLog_DispatchElectronicOrder': 'OrderStatusLogDispatchElectronicOrder'
'OrderStatusLog_Archived': 'OrderStatusLogArchived'
'OrderStatusLog_Submitted': 'OrderStatusLogSubmitted'
'OrderStatusLog_Cancel': 'OrderStatusLogCancel'
'OrderStatusLog_PaymentCheck': 'OrderStatusLogPaymentCheck'
'OrderStatusLog_Dispatch': 'OrderStatusLogDispatch'
'OrderStatusLog_DispatchPhysicalOrder': 'OrderStatusLogDispatchPhysicalOrder'
'CheckoutPage_StepDescription': 'CheckoutPageStepDescription'
'OrderAttribute_Group': 'OrderAttributeGroup'
'OrderModifier_Descriptor': 'OrderModifierDescriptor'
'EcommercePayment_Test': 'EcommercePaymentTest'
'EcommercePayment_TestSuccess': 'EcommercePaymentTestSuccess'
'EcommercePayment_TestFailure': 'EcommercePaymentTestFailure'
'EcommercePayment_TestPending': 'EcommercePaymentTestPending'
'EcommercePayment_Success': 'EcommercePaymentSuccess'
'EcommercePayment_Failure': 'EcommercePaymentFailure'
'EcommercePayment_Processing': 'EcommercePaymentProcessing'
'EcommercePayment_Result': 'EcommercePaymentResult'
'ExchangeRateProvider_Dummy': 'ExchangeRateProviderDummy'

