####
#### FORMAT:
####
####    PATH (relative to root folder of module)
####        LANGUAGE (php / ss / js / css / etc... to use more than one, you can use php|inc)
####            FindKey
####                R: replace with entry - you can leave empty to keep it as the find... in that case you should add a comment
####                C: comment - this makes it a complex replacement.
####                I: ignore case (default is case sensitive)


'.':

    'php':
        'ReadOnlyField':
            R: "ReadOnlyField"
            C: "Does this field contain HTML in the value? If so, you will need to check if the html has been escaped or is displaying correctly."
            I: true
        'ArrayList':
            R: "ArrayList"
            C: "Test this still works as expected. ArrayList should now be more consistent with DataList: https://github.com/silverstripe/silverstripe-framework/commit/f6fe1427c286fa5fc58b83cd10d84bf5930889e2"
            I: true
